answer.py:101:0: R0914: Too many local variables (16/15) (too-many-locals)
answer.py:122:28: R1718: Consider using a set comprehension (consider-using-set-comprehension)
answer.py:172:17: W0621: Redefining name 'report_data' from outer scope (line 184) (redefined-outer-name)
answer.py:184:4: C0103: Constant name "report_data" doesn't conform to UPPER_CASE naming style (invalid-name)
answer.py:3:0: W0611: Unused datetime imported from datetime (unused-import)

------------------------------------------------------------------
Your code has been rated at 8.40/10 (previous run: 8.30/10, +0.10)
